"""empty message

Revision ID: 1f119f1ea852
Revises: ef4f5d0dce05
Create Date: 2022-10-19 09:00:38.826310

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1f119f1ea852"
down_revision = "ef4f5d0dce05"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "race",
        sa.Column("competition_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.drop_constraint("race_competion_id_fkey", "race", type_="foreignkey")
    op.create_foreign_key(None, "race", "competition", ["competition_id"], ["id"])
    op.drop_column("race", "competion_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "race",
        sa.Column(
            "competion_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "race", type_="foreignkey")
    op.create_foreign_key(
        "race_competion_id_fkey", "race", "competition", ["competion_id"], ["id"]
    )
    op.drop_column("race", "competition_id")
    # ### end Alembic commands ###
