"""empty message

Revision ID: 3ed3fdd7be26
Revises: 86c1017ef0df
Create Date: 2022-10-18 14:50:44.194261

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3ed3fdd7be26"
down_revision = "86c1017ef0df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    boat = postgresql.ENUM("ILCA_4", "ILCA_6", "ILCA_7", name="boat")
    boat.create(op.get_bind())

    op.add_column(
        "competition",
        sa.Column(
            "boat", sa.Enum("ILCA_4", "ILCA_6", "ILCA_7", name="boat"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("competition", "boat")
    # ### end Alembic commands ###
