"""empty message

Revision ID: 6610cd79f5a6
Revises: 7657865f600b
Create Date: 2022-10-18 16:18:23.656113

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "6610cd79f5a6"
down_revision = "7657865f600b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("race", sa.Column("competion_id", postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, "race", "competition", ["competion_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "race", type_="foreignkey")
    op.drop_column("race", "competion_id")
    # ### end Alembic commands ###
