"""empty message

Revision ID: 7657865f600b
Revises: 3ed3fdd7be26
Create Date: 2022-10-18 15:01:54.310015

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7657865f600b"
down_revision = "3ed3fdd7be26"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("competition", sa.Column("start_date", sa.Date(), nullable=False))
    op.add_column("competition", sa.Column("end_date", sa.Date(), nullable=False))
    op.create_index(
        op.f("ix_competition_end_date"), "competition", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_competition_start_date"), "competition", ["start_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_competition_start_date"), table_name="competition")
    op.drop_index(op.f("ix_competition_end_date"), table_name="competition")
    op.drop_column("competition", "end_date")
    op.drop_column("competition", "start_date")
    # ### end Alembic commands ###
