"""empty message

Revision ID: 86c1017ef0df
Revises: 3e62970b6f13
Create Date: 2022-10-18 13:10:18.425960

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "86c1017ef0df"
down_revision = "3e62970b6f13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_competitor_sail_nr", table_name="competitor")
    op.create_index(
        op.f("ix_competitor_sail_nr"), "competitor", ["sail_nr"], unique=True
    )
    op.add_column("position", sa.Column("sail_nr", sa.BigInteger(), nullable=True))
    op.drop_constraint("position_competitor_id_fkey", "position", type_="foreignkey")
    op.create_foreign_key(None, "position", "competitor", ["sail_nr"], ["sail_nr"])
    op.drop_column("position", "competitor_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "position",
        sa.Column(
            "competitor_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "position", type_="foreignkey")
    op.create_foreign_key(
        "position_competitor_id_fkey",
        "position",
        "competitor",
        ["competitor_id"],
        ["id"],
    )
    op.drop_column("position", "sail_nr")
    op.drop_index(op.f("ix_competitor_sail_nr"), table_name="competitor")
    op.create_index("ix_competitor_sail_nr", "competitor", ["sail_nr"], unique=False)
    # ### end Alembic commands ###
