"""empty message

Revision ID: 8762dca86d60
Revises: 9e65ee678af6
Create Date: 2022-10-17 17:52:12.190572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8762dca86d60'
down_revision = '9e65ee678af6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('competitor', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('position', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('race', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'updated_at')
    op.drop_column('position', 'updated_at')
    op.drop_column('competitor', 'updated_at')
    op.drop_column('competition', 'updated_at')
    # ### end Alembic commands ###
