"""empty message

Revision ID: e51b90bfa49d
Revises: 1f119f1ea852
Create Date: 2022-11-29 10:10:02.395398

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e51b90bfa49d"
down_revision = "1f119f1ea852"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_competitor_sail_nr", table_name="competitor")
    op.create_index(
        op.f("ix_competitor_sail_nr"), "competitor", ["sail_nr"], unique=False
    )
    op.create_unique_constraint(
        "_competition_id_sail_nr_uc", "competitor", ["competition_id", "sail_nr"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_competition_id_sail_nr_uc", "competitor", type_="unique")
    op.drop_index(op.f("ix_competitor_sail_nr"), table_name="competitor")
    op.create_index("ix_competitor_sail_nr", "competitor", ["sail_nr"], unique=False)
    # ### end Alembic commands ###
