"""empty message

Revision ID: ef4f5d0dce05
Revises: 6610cd79f5a6
Create Date: 2022-10-18 17:03:47.475234

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ef4f5d0dce05"
down_revision = "6610cd79f5a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "competition",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "competitor",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "position",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "race",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("race", "created_at")
    op.drop_column("position", "created_at")
    op.drop_column("competitor", "created_at")
    op.drop_column("competition", "created_at")
    # ### end Alembic commands ###
